services:
  nextjs:
    image: node:22.3.0
    working_dir: /src/app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start"